# Generated by Django 5.2.9 on 2026-01-05 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('is_online', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('policy', models.CharField(choices=[('ALLOW_ALL', 'Liberar Tudo'), ('BLOCK_ALL', 'Bloquear Tudo'), ('READ_ONLY', 'Apenas Leitura')], default='ALLOW_ALL', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='USBLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('device_id', models.CharField(max_length=255)),
                ('action_taken', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usb_logs', to='core.agent')),
            ],
        ),
    ]
