# Generated by Django 5.2.9 on 2026-01-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_whitelisteddevice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usblog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='usblog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usblog',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
